global:
  scrape_interval: 15s  # how often to scrape targets

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Example for monitoring a Node Exporter (system metrics)
  - job_name: 'node_exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'flask_app'
    static_configs:
      - targets: ['host.docker.internal:8000']

